const dashboardData = [
  {
    id: "axis1",
    title: "Databricks Infra & Security",
    color: "#0078d4",
    modules: [
        { id: "1.01", title: "Azure Databricksの全体像とVNet構築", path: "Axis1/1.01_Azure_Databricks_VNet_Injection.md"},
        { id: "1.02", title: "プライベートリンクによる完全閉域化", path: "Axis1/1.02_Private_Link_Architectures.md"},
        { id: "1.03", title: "Control Plane と Compute Plane の物理的境界", path: "Axis1/1.03_Control_vs_Compute_Plane.md"},
        { id: "1.04", title: "Entra ID Service Principals と Managed Identities (MSI)", path: "Axis1/1.04_Managed_Identities_SPN.md"},
        { id: "1.05", title: "AzureにおけるRBAC設計", path: "Axis1/1.05_Azure_RBAC_Least_Privilege.md"},
        { id: "1.06", title: "Unity Catalog (UC) の全体アーキテクチャ", path: "Axis1/1.06_Unity_Catalog_Metastore_Architecture.md"},
        { id: "1.07", title: "UCの階層構造（Catalog > Schema > Table）", path: "Axis1/1.07_UC_Three_Level_Namespace.md"},
        { id: "1.08", title: "ADLS Gen2: 外部ロケーション vs マネージドテーブル", path: "Axis1/1.08_Managed_vs_External_Tables.md"},
        { id: "1.09", title: "UCパーミッション：GRANT/REVOKE 構文", path: "Axis1/1.09_UC_Privileges_and_Permissions.md"},
        { id: "1.10", title: "データガバナンス：Row/Col Securityの実装", path: "Axis1/1.10_Row_and_Column_Security_UI.md"},
        { id: "1.11", title: "クラスタポリシー：JSONによるコスト制御", path: "Axis1/1.11_Cluster_Policies_and_Governance.md"},
        { id: "1.12", title: "パーソナル・コンピュート vs 共有クラスタ", path: "Axis1/1.12_Personal_vs_Shared_Compute.md"},
        { id: "1.13", title: "スポットインスタンス（Azure Spot VM）", path: "Axis1/1.13_Azure_Spot_VMs_Strategy.md"},
        { id: "1.14", title: "Azure Key Vault連携 と Secretsの運用", path: "Axis1/1.14_Azure_Key_Vault_Integration.md"},
        { id: "1.15", title: "Log Analytics と 診断設定 (Diagnostics)", path: "Axis1/1.15_Monitoring_Diagnostics_Logs.md"},
        { id: "1.16", title: "Serverless SQL Warehouse と Jobs", path: "Axis1/1.16_Serverless_Compute_Architectures.md"},
        { id: "1.17", title: "Databricks REST APIによる自動化", path: "Axis1/1.17_Databricks_REST_API_Basics.md"},
        { id: "1.18", title: "Terraform (IaC) を用いた自動構築", path: "Axis1/1.18_Infrastructure_as_Code_Terraform.md"},
        { id: "1.19", title: "Databricks Asset Bundles (DABs) 概念", path: "Axis1/1.19_Databricks_Asset_Bundles_DABs.md"},
        { id: "1.20", title: "DABs を用いた databricks.yml 構成", path: "Axis1/1.20_DABs_YAML_Configuration.md"},
        { id: "1.21", title: "Git連携・GitHub Actions による CI/CD", path: "Axis1/1.21_Git_CI_CD_Best_Practices.md"},
        { id: "1.22", title: "DBU と クラウドコストモニタリング", path: "Axis1/1.22_DBU_and_Cost_Management.md"},
        { id: "1.23", title: "Databricks SQL ウェアハウスのサイジング", path: "Axis1/1.23_Databricks_SQL_Sizing.md"},
        { id: "1.24", title: "Disaster Recovery (DR) 設計", path: "Axis1/1.24_Disaster_Recovery_Standard.md"},
        { id: "1.25", title: "Azure Private DNS ゾーンと名前解決", path: "Axis1/1.25_Azure_Private_DNS_Resolution.md"}
    ]
  },
  {
    id: "axis2",
    title: "Data Eng & Spark Internals",
    color: "#ff3621",
    modules: [
        { id: "2.01", title: "Sparkクラスタの真実：Driver/Worker角色", path: "Axis2/2.01_Spark_Clusters_Drivers_Executors.md"},
        { id: "2.02", title: "RDD, DataFrame, Dataset API と Catalyst", path: "Axis2/2.02_RDD_DataFrame_Dataset_Evolution.md"},
        { id: "2.03", title: "Spark実行計画：Jobs, Stages, Tasks", path: "Axis2/2.03_Spark_Jobs_Stages_Tasks.md"},
        { id: "2.04", title: "Narrow vs Wide変換 と Shuffle", path: "Axis2/2.04_Narrow_vs_Wide_Transformations.md"},
        { id: "2.05", title: "OOM の根本原因とメモリ管理", path: "Axis2/2.05_Memory_OOM_Root_Causes.md"},
        { id: "2.06", title: "shuffle.partitions の罠 (200問題)", path: "Axis2/2.06_Shuffle_Partitions_Tuning.md"},
        { id: "2.07", title: "データ・スキュー検知と Saltキー分散", path: "Axis2/2.07_Data_Skew_and_Salting.md"},
        { id: "2.08", title: "Adaptive Query Execution (AQE)", path: "Axis2/2.08_Adaptive_Query_Execution_AQE.md"},
        { id: "2.09", title: "Broadcast Join vs Sort Merge Join", path: "Axis2/2.09_Join_Strategies_Internal.md"},
        { id: "2.10", title: "Delta Lake 内部構造：ログとParquet", path: "Axis2/2.10_Delta_Lake_Deep_Structure.md"},
        { id: "2.11", title: "ADLS上の ACIDトランザクションの仕組み", path: "Axis2/2.11_ACID_Transaction_Mechanisms.md"},
        { id: "2.12", title: "タイムトラベル（Time Travel）", path: "Axis2/2.12_Time_Travel_and_Snapshots.md"},
        { id: "2.13", title: "OPTIMIZE と Small File Problem", path: "Axis2/2.13_OPTIMIZE_Small_Files_Problem.md"},
        { id: "2.14", title: "V-Order と Z-Order クラスタリング", path: "Axis2/2.14_VOrder_and_ZOrder_Clustering.md"},
        { id: "2.15", title: "VACUUM：古いファイルの物理削除", path: "Axis2/2.15_VACUUM_Cleanup_Retention.md"},
        { id: "2.16", title: "メダリオン・アーキテクチャ全体設計", path: "Axis2/2.16_Medallion_Architecture_Design.md"},
        { id: "2.17", title: "Bronze層の実装原則", path: "Axis2/2.17_Bronze_Layer_Implementation.md"},
        { id: "2.18", title: "Silver層の実装論理", path: "Axis2/2.18_Silver_Layer_Cleansing.md"},
        { id: "2.19", title: "Gold層の設計", path: "Axis2/2.19_Gold_Layer_Aggregations.md"},
        { id: "2.20", title: "バッチ処理 vs 構造化ストリーミング", path: "Axis2/2.20_Batch_vs_Streaming_Paradigm.md"},
        { id: "2.21", title: "Watermarking（遅延データの破棄）", path: "Axis2/2.21_Streaming_Watermarking.md"},
        { id: "2.22", title: "Auto Loader とスキーマ進化", path: "Axis2/2.22_Auto_Loader_CloudFiles.md"},
        { id: "2.23", title: "Delta Live Tables (DLT) 入門", path: "Axis2/2.23_Delta_Live_Tables_Intro.md"},
        { id: "2.24", title: "DLT Expectations：品質チェック", path: "Axis2/2.24_DLT_Quality_Expectations.md"},
        { id: "2.25", title: "変更データキャプチャ（CDC）の実装", path: "Axis2/2.25_Change_Data_Capture_CDC.md"}
    ]
  },
  {
    id: "axis3",
    title: "Enterprise Design & Ops",
    color: "#10b981",
    modules: [
        { id: "3.01", title: "良い「基本設計書」の条件", path: "Axis3/3.01_Enterprise_Design_Fundamentals.md"},
        { id: "3.02", title: "構成図と要件定義書の落とし込み", path: "Axis3/3.02_Architecture_and_Requirements.md"},
        { id: "3.03", title: "ネットワーク仕様書設計", path: "Axis3/3.03_Network_Security_Design.md"},
        { id: "3.04", title: "データ連携設計：マッピング表", path: "Axis3/3.04_Data_Source_Target_Mapping.md"},
        { id: "3.05", title: "DB論理設計：ER図とDict", path: "Axis3/3.05_Logical_Database_Design.md"},
        { id: "3.06", title: "I/F仕様：API vs ファイル連携", path: "Axis3/3.06_Interface_Specifications.md"},
        { id: "3.07", title: "非機能要件（NFR）の定義", path: "Axis3/3.07_Non_Functional_Requirements.md"},
        { id: "3.08", title: "エラーハンドリング方針書", path: "Axis3/3.08_Error_Handling_Policy.md"},
        { id: "3.09", title: "冪等性とリトライポリシー", path: "Axis3/3.09_Idempotency_and_Retries.md"},
        { id: "3.10", title: "バッチジョブフロー設計図", path: "Axis3/3.10_Job_Flow_and_Workflows.md"},
        { id: "3.11", title: "テストスコープと同値分割", path: "Axis3/3.11_Test_Specifications_Scoping.md"},
        { id: "3.12", title: "単体テスト(UT)戦略：pytest", path: "Axis3/3.12_Unit_Testing_and_PySpark.md"},
        { id: "3.13", title: "ローカル開発とMock化", path: "Axis3/3.13_Mocking_and_Environment_Variables.md"},
        { id: "3.14", title: "結合テスト(IT)：正常系と異常系", path: "Axis3/3.14_Integration_Testing_Strategies.md"},
        { id: "3.15", title: "インフラ基盤の結合テスト", path: "Axis3/3.15_Infrastructure_Integration_Testing.md"},
        { id: "3.16", title: "テストデータ合成とマスキング", path: "Axis3/3.16_Test_Data_Synthesis.md"},
        { id: "3.17", title: "受入テスト(UAT)と欠陥管理", path: "Axis3/3.17_UAT_and_Defect_Management.md"},
        { id: "3.18", title: "システム運用手順書の全体像", path: "Axis3/3.18_Operations_Manual_Standards.md"},
        { id: "3.19", title: "監視（Monitoring）設計", path: "Axis3/3.19_Monitoring_Design_Patterns.md"},
        { id: "3.20", title: "アラート閾値の決定とノイズ回避", path: "Axis3/3.20_Alerting_Thresholds_Noise.md"},
        { id: "3.21", title: "障害対応 Runbook の書き方", path: "Axis3/3.21_Incident_Response_Runbooks.md"},
        { id: "3.22", title: "Triage（切り分け）：ログ追跡", path: "Axis3/3.22_Error_Triage_and_Tracing.md"},
        { id: "3.23", title: "リカバリ手順とBackfillフロー", path: "Axis3/3.23_Recovery_Backfill_Manual.md"},
        { id: "3.24", title: "構成管理・リリース手順書", path: "Axis3/3.24_Deployment_and_Rollback_Manual.md"},
        { id: "3.25", title: "ドキュメントの構成管理・レビュー", path: "Axis3/3.25_Document_Governance.md"}
    ]
  },
  {
    id: "axis4",
    title: "Consulting & Soft Skills",
    color: "#8b5cf6",
    modules: [
        { id: "4.01", title: "エンジニアの「報連相」プロの振る舞い", path: "Axis4/4.01_Ho_Ren_So_Professional.md"},
        { id: "4.02", title: "PREP法による圧倒的な伝達力", path: "Axis4/4.02_PREP_Method_Communication.md"},
        { id: "4.03", title: "「期待値コントロール」最強の盾", path: "Axis4/4.03_Expectation_Management.md"},
        { id: "4.04", title: "リスク・コミュニケーション術", path: "Axis4/4.04_Risk_and_Accident_Communication.md"},
        { id: "4.05", title: "Bad News First：心理的安全性", path: "Axis4/4.05_Bad_News_First_Culture.md"},
        { id: "4.06", title: "ステークホルダー・マッピング", path: "Axis4/4.06_Stakeholder_Mapping.md"},
        { id: "4.07", title: "アジェンダと動ける議事録", path: "Axis4/4.07_Agendas_and_Actionable_Minutes.md"},
        { id: "4.08", title: "非同期通信（Teams/Slack）礼法", path: "Axis4/4.08_Asynchronous_Communication_Etiquette.md"},
        { id: "4.09", title: "レビューでの「トーン＆マナー」", path: "Axis4/4.09_Review_Etiquette_and_Tone.md"},
        { id: "4.10", title: "テクニカルライティング：ターゲット特定", path: "Axis4/4.10_Technical_Writing_Target_Audience.md"},
        { id: "4.11", title: "曖昧さの排除：絶対数値化のみ", path: "Axis4/4.11_Technical_Writing_Removing_Ambiguity.md"},
        { id: "4.12", title: "能動態と受動態の使い分け", path: "Axis4/4.12_Active_vs_Passive_Voices.md"},
        { id: "4.13", title: "BLUF型（結論先出し）構成", path: "Axis4/4.13_BLUF_Communication_Logic.md"},
        { id: "4.14", title: "箇条書きと表の極意", path: "Axis4/4.14_Bullet_Points_and_Tables.md"},
        { id: "4.15", title: "図解の色彩・構図術 (Mermaid)", path: "Axis4/4.15_Visualizing_Architecture_Best_Practices.md"},
        { id: "4.16", title: "命名規則：全体の一貫性", path: "Axis4/4.16_Naming_Conventions_Consistency.md"},
        { id: "4.17", title: "要求引き出し：深掘りの質問術", path: "Axis4/4.17_Requirement_Gathering_Mastery.md"},
        { id: "4.18", title: "スコープ・クリープにNoと言う法", path: "Axis4/4.18_Scope_Creep_Management.md"},
        { id: "4.19", title: "コンフリクト・調停術", path: "Axis4/4.19_Conflict_Management_and_Consensus.md"},
        { id: "4.20", title: "ステータス報告：RAG基準", path: "Axis4/4.20_Status_Reporting_Standards.md"},
        { id: "4.21", title: "工数見積もり：3点見積もり法", path: "Axis4/4.21_Estimation_Principles.md"},
        { id: "4.22", title: "DoD (完了の定義) の合意", path: "Axis4/4.22_Definition_of_Done_DoD.md"},
        { id: "4.23", title: "ポストモーテム：非難なき振り返り", path: "Axis4/4.23_Post_Mortem_Culture.md"},
        { id: "4.24", title: "ナレッジ共有：Wiki戦略", path: "Axis4/4.24_Knowledge_Sharing_Impact.md"},
        { id: "4.25", title: "Associate 試験：最終対策シナリオ", path: "Axis4/4.25_Associate_Exam_and_Career_Goal.md"}
    ]
  }
];
